# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: PPML
email: nteetor@hsph.harvard.edu
description: > # this means to ignore newlines until "baseurl:"
  Harvard T.H. Chan School of Public Health Prevention Policy Modeling Lab
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

workflows:
  -
    type: git
    heading: Working with GitHub, git, and the command line
    order:
      - config.html
      - help.html
      - add.html
      - commit.html
  -
    type: rstudio
    heading: Getting started with RStudio projects, version control, and R packages

# Collection settings
collections:
  - descriptions
  - figures
  - examples
    
defaults:
  -
    scope:
      path: _examples/git
      type: examples
    values:
      layout: example
      type: git
  -
    scope:
      path: _examples/rstudio/project
      type: examples
    values:
      layout: example
      type:
        - rstudio
        - project
      heading: Getting started with RStudio projects
  -
    scope:
      path: _descriptions/git
      type: descriptions
    values:
      layout: description
      type: git
  -
    scope:
      path: _descriptions/rstudio/project
      type: descriptions
    values:
      layout: description
      type:
        - rstudio
        - project
      
# Build settings
markdown: kramdown
exclude: ["README.md"]
